# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-step0:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow 0 without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: step0
          token: ${{ secrets.PAT }}
          inputs: '{ "environment": "testenv" }'
  build-step1:
    runs-on: ubuntu-latest
    needs: build-step0
    steps:   
      - name: Invoke workflow 1 without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: step1
          token: ${{ secrets.PAT }}